### ISSUE TITLE
タスクとラインを登録できるようにする

### ISSUE THREAD

**Issue by kimuray** [kimuray/dic_memo#18]
## 概要
画面遷移ベースでラインの登録、タスクの登録を出来るようにする

## 対応内容
- [x] ラインモデルを作成
- [x] タスクモデルを作成
- [x] 画面からライン登録、タスク登録をできるようにする

**Comment by shibatadaiki** [comment]
タスクに関しては、エントリーを作らないとうまく作成できないので、エントリーが完成した後に機能追加する予定
