### ISSUE TITLE
プロジェクトにメンバーを追加できる機能を作成する

### ISSUE THREAD

**Issue by kimuray** [kimuray/dic_memo#5]
## 概要
プロジェクトにメンバーをアサインできる画面と機能を作成する

## 対応内容
- [x] assignテーブルの作成
- [x] メンバーアサイン画面の作成
- [x] アサインしたいメンバーの欄にメールアドレスをカンマ区切りで入力するとuserレコードを作りながらがチームに自動で登録されるようにする
  * userレコードがすでに存在する場合はuserレコードは作成しないようにする

**Comment by shibatadaiki** [comment]
修正中〜〜
