### ISSUE TITLE
プロフィール編集機能を作成する

### ISSUE THREAD

**Issue by kimuray** [kimuray/dic_memo#6]
## 概要
ユーザーのプロフィール編集機能を作成する

## 対応内容
- [x] プロフィール画像を登録できるようにする
  * 画像アップローダーはpaperclip
- [x] プロフィール編集画面を作成する
- [x] 編集項目はメールアドレス、名前、プロフィール画像、パスワード

**Comment by shibatadaiki** [comment]
update処理かけるとなんかデバイスがログアウトする

**Comment by shibatadaiki** [comment]
デフォルト30分らしいのになぜ？

**Comment by shibatadaiki** [comment]
あとボタンに色がつかない。。( 'ω' )

**Comment by shibatadaiki** [comment]
読み込みミスってる？
